name: Build and merge into gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    services:
      plantuml:
        image: plantuml/plantuml-server:jetty
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Ensures Ruby version is compatible with Bundler 2.5.6

      - name: Add Ruby Gems to PATH
        run: echo "/github/home/.gem/ruby/3.0.0/bin" >> $GITHUB_PATH

      - name: Remove bundle cache
        run: rm -rf vendor/bundle

      - name: Install Bundler 2.5.6
        run: gem install bundler -v 2.5.6 # Explicitly install required Bundler version

      - name: Bundle install
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Verify Ruby Version
        run: ruby -v

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ''
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: ''
          actor: ''
          pre_build_commands: ''
