name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This should be the branch containing your Jekyll site source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version you need for your Jekyll site

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Site
      run: |
        bundle exec jekyll build -d build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: build     # The folder the action should deploy.
